### ISSUE TITLE
job

### ISSUE THREAD

**Issue by n0mad01** [dparlevliet/backbone.simplerouter#1]
hi, im n0mad01 the maintainer of the node.bittrex.api lib which you contributed already several times.

i didn't know how to reach you otherwise, so excuse for the unusual way through an issue but you can remove this comment at any time.

i'm trying to reach you because i have a proposal to make a server/api/wallet software and wanted to ask you if you're interested in helping me (of course for payment).

waiting for your reply,
best regards
Adrian

**Comment by dparlevliet** [comment]
Hey, thanks for the offer but unfortunately right now I have too many active projects on top of my full-time job - adding another one would lead to a divorce lol If you're putting it on github feel free to add me and if I see an issue I think I can solve quickly I'll be happy to help - for now I have to stay choosey.

**Comment by n0mad01** [comment]
i see, that's a pity.

if you change your mind let me know, it's a big project and i can always need competent people ;)
